Repository FRCTeam3255/2025_Robot_Code, pull requests merged in 2025-03, with the labels that each got.

#314 Update README.md o(TヘTo)
  README.md
  assets/2025Winner.jpg
  assets/2025_compbot_1.0.jpg
  assets/2025_controllermap.png
  assets/2025_statemachine.png
  assets/Blue_Banner_PHR.jpg
  assets/Innovation_In_Control_Award.png
  assets/PHR_Team_Photo.jpg
  assets/State_Machine_2.0.png
  assets/robot_name_design_2025.png
Labels: 📖 Documentation

#379 Update processor auto align angle （*゜ー゜*）
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/DriveManual.java
Labels: 🤖 Tested on bot

#380 Made the L1 sequence (。>︿<)_
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/states/scoring/ScoringCoral.java
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: ✨ Code Good - Ready to Test

#398 made the elevator go up when ejecting coral also go back down when do…
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/states/first_scoring_element/EjectCoral.java
  src/main/java/frc/robot/commands/states/prep_algae/PrepAlgaeZero.java
  src/main/java/frc/robot/commands/states/prep_algae/PrepAlgaeZeroWithCoral.java
  src/main/java/frc/robot/commands/states/prep_algae/PrepNet.java
  src/main/java/frc/robot/commands/states/prep_algae/PrepNetWithCoral.java
  src/main/java/frc/robot/commands/states/prep_algae/PrepProcessor.java
  src/main/java/frc/robot/commands/states/prep_algae/PrepProcessorWithCoral.java
  src/main/java/frc/robot/commands/states/prep_coral/PrepCoralLv.java
  src/main/java/frc/robot/commands/states/prep_coral/PrepCoralLvWithAlgae.java
  src/main/java/frc/robot/commands/states/prep_coral/PrepCoralZero.java
  src/main/java/frc/robot/commands/states/prep_coral/PrepCoralZeroWithAlgae.java
  src/main/java/frc/robot/commands/states/scoring/ScoringAlgae.java
  src/main/java/frc/robot/commands/states/scoring/ScoringAlgaeWithCoral.java
  src/main/java/frc/robot/commands/states/scoring/ScoringCoral.java
  src/main/java/frc/robot/commands/states/scoring/ScoringCoralWithAlgae.java
  src/main/java/frc/robot/commands/states/second_scoring_element/EjectCoralWithAlgae.java
  src/main/java/frc/robot/subsystems/Elevator.java
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: 🤖 Tested on bot

#406 Fix HAS_ALGAE spam (o゜▽゜)o☆
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/states/first_scoring_element/CleaningL2Reef.java
  src/main/java/frc/robot/commands/states/first_scoring_element/CleaningL3Reef.java
  src/main/java/frc/robot/commands/states/first_scoring_element/IntakingAlgaeGround.java
  src/main/java/frc/robot/commands/states/hold_scoring_elements/HasAlgae.java
  src/main/java/frc/robot/commands/states/hold_scoring_elements/HasCoralAndAlgae.java
  src/main/java/frc/robot/commands/states/second_scoring_element/CleaningL2ReefWithCoral.java
  src/main/java/frc/robot/commands/states/second_scoring_element/CleaningL3ReefWithCoral.java
Labels: 🛑 Untested, ✨ Code Good - Ready to Test

#403 disable manual climb go back to none after prep climb (　o=^•ェ•)o
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/states/climbing/ClimberDeploying.java
  src/main/java/frc/robot/subsystems/Climber.java
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: ✨ Code Good - Ready to Test

#409 make manual climber deploying go to manual climber deploying ¯\_(ツ)_/¯
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: ✨ Code Good - Ready to Test

#408 Fix Coral Override (☆-ｖ-)
  src/main/java/frc/robot/commands/states/hold_scoring_elements/HasCoral.java
  src/main/java/frc/robot/commands/states/hold_scoring_elements/HasCoralAndAlgae.java
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: 🛑 Untested, ✨ Code Good - Ready to Test

#401 reset auto index to 0 .·´¯`(>▂<)´¯`·.
  src/main/java/frc/robot/RobotContainer.java
Labels: ✨ Code Good - Ready to Test

#383 Reef Auto-Align based on Rotation 🌀
  assets/2025_controllermap.png
  assets/Joystick_XboxControllerRed/config.json
  assets/Joystick_XboxControllerRed/image.png
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/DriveManual.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
Labels: 💻 Tested in sim

#324 create auto align to algae (๐˃̶ᗜ˂̶๐)
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/DriveManual.java
  src/main/java/frc/robot/commands/states/hold_scoring_elements/HasAlgae.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: 🤖 Tested on bot, ✨ Code Good - Ready to Test

#441 Fix parameter order in elevator position checks for clarity
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: 🤖 Tested on bot, ✨ Code Good - Ready to Test

#447 Update climber retract velocity constant
  src/main/java/frc/robot/Constants.java
Labels: 🤖 Tested on bot, ✨ Code Good - Ready to Test
