Repository FRCTeam3255/2025_Robot_Code, pull requests merged in 2025-01, with the labels that each got.

#157 Added Logic to Elevator
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/commands/states/PrepAlgaeZero.java
  src/main/java/frc/robot/commands/states/PrepCoralLv.java
  src/main/java/frc/robot/commands/states/PrepCoralZero.java
  src/main/java/frc/robot/commands/states/PrepNet.java
  src/main/java/frc/robot/commands/states/PrepProcessor.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: 💻 Tested in sim

#172 added elevator motion magic o(*￣▽￣*)o
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: 🤖 Tested on bot

#160 Zeroing Elevator
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Zeroing/ManualZeroElevator.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: 🛑 Untested

#188 #112 add manual algae intake zeroing
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Zeroing/ManualZeroAlgaeIntake.java
  src/main/java/frc/robot/subsystems/AlgaeIntake.java
Labels: 🛑 Untested

#186 179 add motion magic to algae pivot motor
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/subsystems/AlgaeIntake.java
Labels: 💻 Tested in sim

#209 Make elevator move o(〃＾▽＾〃)o
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/states/IntakeCoralHopper.java
  src/main/java/frc/robot/subsystems/StateMachine.java
Labels: 💻 Tested in sim

#192 174 implement automatic zeroing
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/Robot.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/Zeroing/ManualZeroAlgaeIntake.java
  src/main/java/frc/robot/commands/Zeroing/ManualZeroElevator.java
  src/main/java/frc/robot/commands/Zeroing/ZeroAlgaeIntake.java
  src/main/java/frc/robot/commands/Zeroing/ZeroElevator.java
  src/main/java/frc/robot/subsystems/AlgaeIntake.java
  src/main/java/frc/robot/subsystems/Elevator.java
Labels: 🤖 Tested on bot

#212 create game piece overrides
  simgui-ds.json
  simgui.json
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/commands/states/EjectingAlgae.java
  src/main/java/frc/robot/commands/states/PlaceCoral.java
  src/main/java/frc/robot/commands/states/ScoringAlgae.java
  src/main/java/frc/robot/subsystems/AlgaeIntake.java
  src/main/java/frc/robot/subsystems/CoralOuttake.java
Labels: 💻 Tested in sim

#211 Set elevator hight and pivot angle
  src/main/java/frc/robot/Constants.java
Labels: 💻 Tested in sim

#214 Add Game Piece Poses
  src/main/java/frc/robot/Constants.java
  src/main/java/frc/robot/RobotContainer.java
  src/main/java/frc/robot/subsystems/Drivetrain.java
  src/main/java/frc/robot/subsystems/RobotPoses.java
Labels: 💻 Tested in sim
